Enital/healthy_hub

src/components/App.jsx
src/components/SignUpForm/SignUpForm.jsx
src/index.css
src/pages/OnePage/OnePage.jsx
src/pages/OnePage/OnePage.module.css
src/pages/SignUp/SignUp.jsx
src/pages/SignUpPage/SignUpPage.jsx
src/variables.css

One and signup pages
Added styles for One page
Updated variables
Create SingUp page and form conponent

One and signup pages

---

src/components/SelectGenderAge/SelectGenderAge.jsx
src/components/SelectGenderAge/SelectGenderAge.module.css
src/components/SignUpForm/SignUpForm.jsx
src/components/YourActivity/YourActivity.jsx
src/components/YourActivity/YourActivity.module.css
src/components/YourGoal/YourGoal.jsx
src/components/YourHealth/YourHealth.jsx
src/components/YourHealth/YourHealth.module.css
src/pages/SignUpPage/SignUpPage.jsx

Signup page (added onSubmit and navigate)

Signup page

---

src/components/App.jsx
src/redux/auth/operations.js

Added isRefreshing to project

---

src/pages/SignIn/SignIn.jsx

Updated sign in fn

---

src/index.css

Custom input

---

src/components/SignUpForm/SignUpForm.jsx
src/components/YourActivity/YourActivity.jsx
src/components/YourActivity/YourActivity.module.css
src/components/YourGoal/YourGoal.jsx
src/components/YourGoal/YourGoal.module.css
src/pages/SignUpPage/SignUpPage.jsx
src/redux/auth/operations.js
src/redux/auth/selectors.js
src/redux/store.js

Register page

---

src/components/SelectGenderAge/SelectGenderAge.module.css
src/components/SignUpForm/SignUpForm.module.css
src/components/YourActivity/YourActivity.module.css
src/components/YourGoal/YourGoal.module.css
src/components/YourHealth/YourHealth.module.css
src/pages/ForgotPassword/ForgotPassword.jsx
src/pages/ForgotPassword/ForgotPassword.module.css
src/pages/OnePage/OnePage.module.css
src/pages/SignIn/SignIn.jsx
src/pages/SignIn/SignIn.module.css

Singup page styles

---

src/pages/SignIn/SignIn.jsx
src/pages/SignIn/SignIn.module.css

Updated SignIn page

---

src/components/RecFoodOnMain/RecFoodOnMain.jsx

Added RecFoodOnMain component

---

src/pages/Main/Main.jsx

Updated container

---

src/components/RecommendedFoodList/RecommendedFoodList.module.css
src/pages/Main/Main.jsx

Updated className

---

src/index.css
src/pages/Main/Main.module.css

Recommended food page

---

src/components/RecFoodOnMain/recFoodOnMain.module.css
src/pages/Main/Main.module.css

Updated containers for Main Page

Updated containers for Main Page

---

src/pages/ForgotPassword/ForgotPassword.jsx

Updated Added ForgotPassword axios function

Updated Added ForgotPassword axios function

---

src/components/RecFoodOnMain/recFoodOnMain.module.css
src/components/RecommendedFoodList/RecommendedFoodList.module.css
src/components/SelectGenderAge/SelectGenderAge.module.css
src/components/SignUpForm/SignUpForm.module.css
src/components/YourHealth/YourHealth.module.css
src/pages/Main/Main.module.css
src/pages/OnePage/OnePage.module.css

 Updated form styles and h2

---

src/components/SelectGenderAge/SelectGenderAge.module.css
src/components/YourHealth/YourHealth.module.css

Fixed minor

---

src/components/SignUpForm/SignUpForm.module.css
src/pages/SignIn/SignIn.module.css

Updated form styles

---

src/components/YourGoal/YourGoal.jsx

Updated goals

---

src/components/Header/Header.jsx
src/components/Header/header.module.css

Reverts Enital/healthy_hub#125

Revert "css tablet header"

---

src/index.js

Reverts Enital/healthy_hub#132

Revert "Add line in index.js"

---

src/index.js

Reverts Enital/healthy_hub#133

Revert "Revert "Add line in index.js""

---

src/components/Header/Header.jsx
src/components/Header/header.module.css

Reverts Enital/healthy_hub#129

Revert "Revert "css tablet header""

---

src/redux/usersGoal/operations.js

Updated endpoint for food-intake

Updated endpoint for food-intake

---

src/components/SignUpForm/SignUpForm.module.css
src/pages/Main/Main.module.css

Updated styles

---

src/redux/auth/sliceFunction.js

Updated auth slice

---

src/pages/SettingsPage/SettingsPage.jsx
src/redux/auth/authSlice.js
src/redux/auth/operations.js
src/redux/auth/sliceFunction.js

Updated slice+dispach on settings page.

Updated slice+dispach on settings page.

---

src/images/icons/inbox.svg
src/index.css
src/pages/SettingsPage/SettingsPage.jsx
src/redux/auth/authSlice.js
src/redux/auth/operations.js
src/redux/auth/sliceFunction.js

Updated change-avatar slice

---

src/pages/SettingsPage/SettingsPage.jsx
src/pages/SettingsPage/settingsPage.module.css

Updated styles for settings page

Updated styles for settings page

---

src/redux/usersGoal/operations.js
src/redux/usersGoal/slice.js

Created slice and operation for PUT /user/food-intake/:id

Created slice and operation for PUT /user/food-intake/:id

---

src/components/ModalDiary/UpdateMealModal/UpdateMealModal.jsx
src/components/Table/Table.jsx

Auth slice

---

src/components/Layout/Layout.jsx
src/index.css

Updated layout bgc

---

src/pages/ForgotPassword/ForgotPassword.jsx

Updated forgot-password-page

---

src/components/ModalDiary/UpdateMealModal/UpdateMealModal.jsx
src/components/ModalDiary/UpdateMealModal/UpdateMealModal.module.css

Updated update-meal-modal styles

Updated update-meal-modal styles

---

src/components/ModalDiary/UpdateMealModal/UpdateMealModal.jsx

Added scrollLock

---

src/pages/SettingsPage/SettingsPage.jsx
src/redux/auth/operations.js

Disabled console.log

---

src/components/SignUpForm/SignUpForm.module.css
src/pages/SignIn/SignIn.module.css

Updated password-eye
